name: Release
on:
  push:
    branches:
      - main

jobs:
  bumpversion:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.tag_version.outputs.new_version }}
      previous_tag: ${{ steps.tag_version.outputs.previous_tag }}
      bump_commit_sha: ${{ steps.bumpversion.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v3
      - name: Get next version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          default_prerelease_bump: false
          dry_run: true
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Create bumpversion
        if: steps.tag_version.outputs.new_version
        run: |
          pip install bump2version
          bump2version --new-version ${{ steps.tag_version.outputs.new_version }} setup.cfg
      - name: Update Changelog
        if: steps.tag_version.outputs.new_version
        uses: stefanzweifel/changelog-updater-action@v1.6.2
        with:
          latest-version: ${{ steps.tag_version.outputs.new_tag }}
          release-notes: ${{ steps.tag_version.outputs.changelog }}
      - name: Push branch
        run: |
          git checkout -b bot/v${{ steps.tag_version.outputs.new_version }}
          git push origin bot/v${{ steps.tag_version.outputs.new_version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          commit-message: "chore: preparing release ${{ steps.tag_version.outputs.new_version }}"
          branch: "bot/v${{steps.tag_version.outputs.new_version}}"
          base: main
